name: aqualog
description: Another project I won't finish

environment:
  sdk: '^3.7.0'

dependencies:
  dart_duckdb: ^1.2.0
  flutter:
    sdk: flutter
  grpc: ^4.0.4
  protobuf: ^4.1.0
  uuid: ^4.0.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.26.2
