name: aqualog
description: Another project I won't finish

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.4
  protobuf: ^4.1.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^3.0.1